"""Regenerate docs/TOPOLOGY_VERIFICATION.md from the model configuration (single source of truth)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ripplecut.engine.dependency import describe_rule
from ripplecut.model.loader import REPO_ROOT, load_model


def main() -> None:
    b = load_model()
    s, meta = b.system, b.system.metadata
    L = ["# Online Boutique Topology Verification\n",
         "Generated by `python scripts/gen_topology_doc.py` from `config/online_boutique_canonical.json`.\n",
         f"Source inspected: {meta['source_repository']} at commit `{meta['source_commit_inspected']}` "
         "(cloned and read during the build; line numbers refer to that commit).\n",
         "Two labels are kept strictly apart (master spec §9, §74):\n",
         "* **SOURCE-BACKED TOPOLOGY** — the call edge exists in the source, with the file/line where it is made "
         "and how an error is handled.",
         "* **RIPPLECUT-MODELED RULE** — the Boolean rule, hard/soft classification, criticality, actions and "
         "costs. These are informed by the source's error handling but are *not* claimed to be Online Boutique "
         "production semantics.\n",
         "## Services (11, frozen by PDF §2.1)\n", "| service | role | criticality (RippleCut policy) |",
         "|---|---|---|"]
    for sv in s.services:
        cls = "critical" if sv.id in s.critical else ("infrastructure" if sv.id in s.infrastructure else "non-critical")
        L.append(f"| {sv.id} | {sv.role.value} | {cls} |")
    L.append("\nExcluded from the model (present in the repository but not among the 11 frozen services):\n")
    for e in b.raw.get("excluded_services", []):
        L.append(f"* `{e['id']}` — {e['reason']}")
    L.append("\n## Call edges and evidence\n")
    L.append("| caller (downstream) | callee (upstream) | strength in model | topology label | evidence |")
    L.append("|---|---|---|---|---|")
    for r in s.rules.values():
        for inp in r.inputs:
            L.append(f"| {r.downstream} | {inp.service} | {inp.strength.value} | {inp.topology} | {inp.evidence} |")
    hard = sum(len(r.hard_upstream) for r in s.rules.values())
    soft = sum(len(r.soft_upstream) for r in s.rules.values())
    L.append(f"\n{hard} hard (propagating) edges and {soft} soft (recorded, non-propagating) edges.\n")
    L.append("## Modeled rules (RIPPLECUT-MODELED)\n")
    for r in s.rules.values():
        L.append(f"* `{describe_rule(r)}` — {r.notes}")
    L.append("\nState meaning used by the model: " + "; ".join(f"{k}: {v}" for k, v in meta["state_meaning"].items()))
    L.append("\n## Interventions (RIPPLECUT-MODELED, hypothetical)\n")
    L.append("None of these mechanisms exists in Online Boutique (PDF §7.1); their effects and costs are model "
             "parameters.\n")
    L.append("| action | cost | effect | precondition on x(0) | label |")
    L.append("|---|---|---|---|---|")
    for a in b.actions.interventions:
        eff = ", ".join([f"{x} UP" for x in sorted(a.effect.set_up)] + [f"{x} DOWN" for x in sorted(a.effect.set_down)])
        pre = ", ".join(f"{p.service} {'UP' if p.state else 'DOWN'}" for p in a.preconditions) or "none"
        L.append(f"| {a.id} | {a.cost} | {eff} | {pre} | {a.metadata.get('label', '')} |")
    L.append("\nDeclared conflicts:\n")
    for c in b.actions.conflicts.values():
        L.append(f"* {' + '.join(sorted(c.actions))}: {c.resolution.value} — {c.rationale}")
    L.append("\n## What is not claimed\n")
    L.append("* No claim that PlaceOrder or the home page behave exactly like these Boolean rules in production "
             "(timeouts, retries, partial rendering and caching are not modeled).")
    L.append("* No 2-of-3 or quorum rule is claimed for Online Boutique; OR/THRESHOLD/GROUP are generic model "
             "capabilities exercised in tests with synthetic models.")
    L.append("* redis-cart failure is not representable in this model; a text mentioning it is rejected as an "
             "unknown component.")
    out = REPO_ROOT / "docs" / "TOPOLOGY_VERIFICATION.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
