"""Regenerate docs/VALIDATION_REPORT.md from a real pytest run and real pipeline runs (no hand-typed numbers)."""
import json
import platform
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ripplecut.pipeline import FaultSpec, RippleCutApp  # noqa: E402

GATES = [
    ("1", "System model validates", "test_model_validation.py"),
    ("2", "Cascade simulator passes unit tests", "test_simulator.py, test_dependency_rules.py"),
    ("3", "Intervention engine passes tests", "test_interventions.py"),
    ("4", "Objective evaluator passes hand-calculated examples", "test_objective.py"),
    ("5", "Exhaustive solver passes known examples", "test_exhaustive.py"),
    ("6", "B&B matches Exhaustive", "test_branch_and_bound.py (400 random seeds x 4 B&B variants + canonical)"),
    ("7", "Validator catches intentionally corrupted results", "test_validator.py"),
    ("8", "Fallback works under solver crash", "test_solver_architecture.py::test_crash_solver_falls_back; "
                                             "test_scenarios_e2e.py::test_resilience_every_fault_mode[*-crash]"),
    ("9", "Fallback works under timeout", "test_solver_architecture.py::test_cooperative_timeout_recorded_and_fallback, "
                                         "::test_stubborn_solver_is_abandoned; test_resilience_every_fault_mode[*-timeout]"),
    ("10", "All canonical scenarios run", "test_scenarios_e2e.py::test_canonical_scenario_matches_hand_derived_expectation"),
    ("11", "End-to-end flow works", "test_scenarios_e2e.py::test_end_to_end_from_natural_language, ::test_ui_api_contract"),
    ("12", "Demo works offline", "test_scenarios_e2e.py::test_demo_runs_offline (sockets blocked)"),
]
SPEC_TESTS = [
    ("§114 tiny A,B,C", "test_simulator.py::test_critical_correctness_tiny_abc; "
                        "test_interventions.py::test_tiny_abc_intervention_restores_everything"),
    ("§115 a1/a2/a3 lexicographic", "test_objective.py::test_exact_lexicographic_order, ::test_hand_calculated_values"),
    ("§116 known optimum, both solvers, validator", "test_branch_and_bound.py::test_bb_known_optimum_and_validator_accepts"),
    ("§117 BadSolver", "test_solver_architecture.py::test_bad_solver_rejected_then_fallback"),
    ("§118 CrashSolver", "test_solver_architecture.py::test_crash_solver_falls_back"),
    ("§119 timeout solver", "test_solver_architecture.py::test_cooperative_timeout_recorded_and_fallback"),
    ("§120 heuristic non-optimal", "test_solver_architecture.py::test_heuristic_valid_but_not_proven_optimal, "
                                   "::test_cross_check_flags_non_optimal_heuristic"),
    ("§121 extensibility 2 -> 3 solvers", "test_solver_architecture.py::test_extensibility_two_then_three_solvers, "
                                          "::test_thirty_solvers_same_code_path"),
    ("§122 architectural integrity", "test_architecture_integrity.py"),
]


def run_pytest():
    with tempfile.TemporaryDirectory() as d:
        xml = Path(d) / "r.xml"
        proc = subprocess.run([sys.executable, "-m", "pytest", "-q", f"--junitxml={xml}"], cwd=ROOT,
                              capture_output=True, text=True)
        root = ET.parse(xml).getroot()
        suite = root if root.tag == "testsuite" else root.find("testsuite")
        per_file = Counter()
        failed = []
        for tc in suite.iter("testcase"):
            mod = tc.get("classname", "").split(".")[-1] + ".py"
            per_file[mod] += 1
            if tc.find("failure") is not None or tc.find("error") is not None:
                failed.append(f"{tc.get('classname')}::{tc.get('name')}")
        summary = {k: suite.get(k) for k in ("tests", "failures", "errors", "skipped", "time")}
        return summary, per_file, failed, proc.returncode


def main() -> None:
    summary, per_file, failed, _rc = run_pytest()
    app = RippleCutApp()
    ok = app.run_scenario("payment_failure")
    bad = app.run_scenario("payment_failure", fault=FaultSpec("wrong_cost"))
    inv = app.run_scenario("payment_failure", fault=FaultSpec("invalid_action"))
    cart = app.run_scenario("cart_failure")
    L = ["# Validation Report\n",
         "Generated by `python scripts/gen_validation_report.py` from a real pytest run and real pipeline runs on "
         f"Python {platform.python_version()} ({platform.platform()}). Nothing below is hand-typed.\n",
         f"**Test run:** {summary['tests']} tests, {summary['failures']} failures, {summary['errors']} errors, "
         f"{summary['skipped']} skipped, {float(summary['time']):.2f} s.\n"]
    if failed:
        L.append("**FAILING TESTS:** " + ", ".join(failed) + "\n")
    L += ["## Implementation gates (master spec §113)\n", "| gate | requirement | evidence (tests) | status |",
          "|---|---|---|---|"]
    status = "PASS" if not failed else "SEE FAILURES"
    for g, req, ev in GATES:
        L.append(f"| {g} | {req} | {ev} | {status} |")
    L += ["\n## Specification tests (master spec §114-§122)\n", "| requirement | test |", "|---|---|"]
    L += [f"| {a} | {b} |" for a, b in SPEC_TESTS]
    L += ["\n## Test inventory\n", "| file | tests |", "|---|---|"]
    L += [f"| tests/{f} | {n} |" for f, n in sorted(per_file.items())]

    L += ["\n## Evidence that solver output is independently validated\n",
          "### 1. Accepted result (payment_failure, primary solver)\n",
          "Validator checks recomputed from the problem definition:\n", "| check | passed | detail |", "|---|---|---|"]
    for c in ok["planner"]["validation"]["checks"]:
        L.append(f"| {c['name']} | {c['passed']} | {c['detail']} |")
    xc = ok["planner"]["verification"]
    L.append(f"\nExact cross-check: **{xc['status']}** — " + "; ".join(
        f"{c['solver']}: {c['verdict']} with plan {c.get('plan')} objective {c.get('objective')}" for c in xc["checks"]))

    def rejected(r, title):
        a = r["planner"]["attempts"][0]
        failed_checks = [c["name"] for c in (a.get("validation") or {}).get("checks", []) if not c["passed"]]
        L.append(f"\n### {title}\n")
        L.append(f"* Resilience label: {r['resilience_test']['label']} (mode `{r['resilience_test']['mode']}`)")
        L.append(f"* Primary attempt: `{a['solver']}` → status `{a['result']['status']}`, outcome `{a['outcome']}`")
        L.append(f"* Validator reason: {a['result']['error']}")
        if failed_checks:
            L.append(f"* Failed checks: {', '.join(failed_checks)}")
        L.append(f"* Final: `{r['status']}` plan {r['result']['plan']} from `{r['result']['selected_solver']}` "
                 f"(fallbacks {r['result']['fallback_count']}), optimality `{r['result']['optimality_status']}`")

    rejected(bad, "2. Corrupted cost is rejected (fault injection `wrong_cost`)")
    rejected(inv, "3. Unknown action is rejected (fault injection `invalid_action`)")
    L.append("\n### 4. Infeasibility is certified independently (cart_failure)\n")
    L.append(f"* Status `{cart['status']}`, certified = {cart['result']['infeasibility_certified']}")
    L.append(f"* Basis: {cart['result']['infeasibility_basis']}")
    L.append("* Certificate: " + json.dumps(cart["explanation"].get("infeasibility", {})))
    L.append("\n## Known limits of this validation\n")
    L.append("* The validator is independent of the solvers but shares the single engine by design (master spec "
             "§97-§99). Engine correctness is covered by hand-calculated and property tests, not by the validator.")
    L.append("* Uncertifiable infeasibility is accepted only from a completed exact search, labeled 'not "
             "independently certified' (tests/test_validator.py::test_uncertifiable_infeasibility_needs_complete_"
             "exact_search).")
    L.append("* All results concern the explicit model; none validates real Online Boutique behavior.")
    content = "\n".join(L) + "\n"
    out = ROOT / "docs" / "VALIDATION_REPORT.md"
    out.write_text(content, encoding="utf-8")
    (ROOT / "VALIDATION_REPORT.md").write_text(content, encoding="utf-8")
    print(f"wrote {out} and root VALIDATION_REPORT.md: {summary}")


if __name__ == "__main__":
    main()
